### ISSUE TITLE
Building on Windows SDL2_IMAGE issue

### ISSUE THREAD

**Issue by SandroWissmann** [Banderi/Ozymandias#9]
Hi again.

I try to compile now also under windows vm to see how far it works there.

However when I run

cmake .. -G "MinGW Makefiles"

I get this output:

`
![Screenshot_20220918_221241](https://user-images.githubusercontent.com/42449992/190926487-98ecf59b-a9b9-401c-a499-f61c068c7f1a.png)

`

So something here complains about SDL_image. However I did not touch the SDL_image folder.

I think maybe the issue here is that I use the latest SDL2 and SLD2 mixer libraries.
However I could not find older ones with MinGW. Like it is mentioned here:
https://github.com/bvschaik/julius/wiki/Building-for-Windows

So I have 

SDL2_mixer-2.62
SDL2-2.24.0

Is that to new maybe?
Do i need the 2.0x versions?

**Comment by crudelios** [comment]
You need the SDL_image for Ozymandias, unlike julius and Augustus where you don't need it. Did you get it?

**Comment by SandroWissmann** [comment]
I was not sure if i have to download it separetly because there is already a tar.gz file in the SDL_image folder. So I just download it like the others and thats it?

**Comment by crudelios** [comment]
I think you need to extract the file somewhere then provide its location like you do for sdl and sdl_mixer.

**Comment by SandroWissmann** [comment]
I downloaded the mingw SDL_Image and added this like the other things for SDL2 like this:

file:///tmp/Spectacle.DqJbCJ/Screenshot_20220919_160730.png

Still no luck. Still get this error:

![Screenshot_20220919_160856](https://user-images.githubusercontent.com/42449992/191037169-93099ca0-ec90-4a4d-bdfd-7cb3a51da450.png)

**Comment by crudelios** [comment]
Try adding it inside the `SDL2` folder.

However, I think the `cmake/FindSDL2_image.cmake` file is incomplete as it does not search in the `ext` folder like `SDL2` and `SDL2_mixer` do.

In that case, you'll need to provide the `-DCMAKE_PREFIX_PATH=<path to the sdl2_image folder>`. That may or may not work.

**Comment by SandroWissmann** [comment]
tried it with abolutes path like you suggest but also no luck:

![Screenshot_20220919_184648](https://user-images.githubusercontent.com/42449992/191070192-02712be3-80ba-48bd-8814-d3467f692c77.png)

All very strange on linux im pretty sure I did not even install sdl_image extra (just install sdl2 and mixer via command line).

Mayb @Banderi knows what he did to set it up (Would be maybe a really good idea to fix instructions how to build on windows)

**Comment by Banderi** [comment]
Ah yes, this was another mess that I threw together to make it compile on my end; I couldn't figure out how to set up SDL2 on my end way back when, and did not dare touch the cmakelists.txt, so...

I forget exactly how I set it up, I'll have to check my CLion files

**Comment by SandroWissmann** [comment]
Mabe its just a version issue with sld and sld_mixer. Maybe check which ones you have in your ext folder.

I also did not know whats with the tar.gz file in the Sdl_image folder.

**Comment by SandroWissmann** [comment]
Just to add. I checked what I have installed under manjaro:

sdl2 2.24.0-1
sdl2_mixer 2.6.2-1
sdl2_image 26.2-1

So that atleast confirms we somehow have to install sd2_image on windows. 

So there is maybe really only something wrong with this build script

**Comment by SandroWissmann** [comment]
I also tried to add sld2_image like this to the main cmake:

find_package(SDL2_image REQUIRED) 

but no luck.

Also with the main CMake I would expect that we have to put all the SDL2 stuff in one folder like this:

![Screenshot_20220919_210522](https://user-images.githubusercontent.com/42449992/191095719-25e7bdff-38c4-4cdd-be7b-d07dd2799830.png)

Then I would expect that somehow FindSDL2_image.cmake would work but looks like still something missing.

Unfortunately my CMake knowledge is quite limited..

**Comment by crudelios** [comment]
Try adding

```
GET_SDL_EXT_DIR(SDL_EXT_DIR "image")
```

To the first line of your `FindSDL_image.cmake` file.

**Comment by SandroWissmann** [comment]
Ok I can try it tomorrow. But ypu say I does not work?

**Comment by Banderi** [comment]
Yeah, it's a huge mess... This is actually of the biggest reasons I want to start fresh, because SDL2 is a huge pain in the butt and I want to have a clean way to build it with clear instructions. I think the way I did it is I manually added the absolute paths to the CLion project, as you have done, and I think that translates into the `-DCMAKE_PREFIX_PATH` flags as mentioned above but I need to check to be sure.

**Comment by SandroWissmann** [comment]
If you look in the above post somehow it was not working with -DCMAKE_PREFIX_PATH. Maybe I still did something wrong.

I remember when I did https://github.com/SandroWissmann/Bricks it was also a huge pain for me just figuring out how to add SDL2 and SDL2_mixer in CMake. But now we have image. Maybe we can also ask for help in the repo from SDL2_image...

**Comment by crudelios** [comment]
Yes, cmake searches the OS library/ include paths on linux automatically,  making things easier.

On windows you have no such specific paths, meaning you have to set things manually.

I don't have time now, but if you adapt the mixer cmake for image (just change the variable names!), you should get it to work

**Comment by SandroWissmann** [comment]
Ok I will try it out tonught and open a branch for it. even if it is not working you can maybe take a look at it to suggest more things we can try.

**Comment by Banderi** [comment]
Just checked my project, here's what I did:
`-DCMAKE_PREFIX_PATH=LIB\64`
`-DSYSTEM_LIBS=false`
It seems I already committed all the files as well, so you should be able to try them out without downloading anything separate.

**Comment by SandroWissmann** [comment]
I tried to fix the cmake like @crudelios  suggested but we still get an error.

See this faulty pull request:
https://github.com/Banderi/Ozymandias/pull/11

Maybe I just forgot something here?

**Comment by SandroWissmann** [comment]
I also tried with the arguments @Banderi suggets on the original master branch but also no luck.

![Screenshot_20220920_170656](https://user-images.githubusercontent.com/42449992/191295011-4dd017be-aaaf-46dd-b02e-64f951728200.png)

This must be really something very stupid we are misssing here...

**Comment by Banderi** [comment]
Keep in mind the LIB folder is in the root directory, so I think if you're calling cmake from inside the build folder, it's not gonna find it like that. Maybe you need ../LIB/64 in your case?

**Comment by SandroWissmann** [comment]
Looks like you did exactly the same as me but somehow not get this complain...

**Comment by Banderi** [comment]
What MinGW version are you using?
I'm using MinGW 9.0.0 with GCC 11.2.0. I used to use 6.00 with GCC 8.1.0 but it stopped working a while back (maybe because of the same issues I was having with C++14? I forget)

**Comment by SandroWissmann** [comment]
GCCis 12.2.0. MinGW im not sure how I can check it but I think its the latest.

**Comment by Banderi** [comment]
Just quickly tested with the latest one, GCC 12.2.0/minGW 11.0.0 and it seemed to generate and compile exactly the same... maybe a problem with CMake?

**Comment by SandroWissmann** [comment]
I used MinGW64 bit.  I thought its right because Windows 10 is 64 bit.

CMake is version 3.24.2

**Comment by Banderi** [comment]
Yeah, was just to make sure; I included the 32 bit files because I had them, but I did not get them to work, and my system is 64 bit as well so had no reason for it.

**Comment by SandroWissmann** [comment]
Do you have anything in your ext/SDL2 folder and also ext/SDL_Image ?

**Comment by Banderi** [comment]
Nothing, apart from an old tar file I had of the library which apparently I committed along. I downloaded the repo fresh to test if I had anything locally that made it compile, but it worked correctly. The only thing that are currently needed in ext (at least for the generation) are expat and tinyfiledialogs.

**Comment by SandroWissmann** [comment]
I got it to work now with the ext/SDL2 folder in the merge request @crudelios fixed. No I just need to find out why make does not work I think its a slghtly different command on linux

**Comment by SandroWissmann** [comment]
actually now both ways work after delete clean the build folder:

Either with 

cmake -DCMAKE_PREFIX_PATH=LIB64 -DYSTEM_LIBS=false .. -G "MinGW Makefiles"

or just 
cmake .. -G "MinGW Makefiles"

with the fixed branch. if you supply in ext/SDL2 all SDL2 Mixer and Image.

**Comment by Banderi** [comment]
Aha! Classic CMake corrupted/partial buildfiles being a nuisance.....

**Comment by SandroWissmann** [comment]
Oh yes. Even me working full time C++. I still fell for it from time to time. Its generally if something is unexplained this can be the solution. I thought between tries i actually deleted the build folder.
